services:
  app:
    image: ghcr.io/jonnefelix/kilimanjaro-tour:latest
    ports:
      - "3010:3000"
    volumes:
      - kili_uploads:/app/backend/uploads
      - kili_db:/app/backend
    restart: always

volumes:
  kili_uploads:
  kili_db:
